//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class AudioTable
    {
        public int Audio_id { get; set; }
        public string Audio_Name { get; set; }
        public string Audio_Description { get; set; }
        public string Audio_Subject { get; set; }
        public string Audio_File { get; set; }

        public HttpPostedFileBase Ado_file { get; set; }
        //public HttpPostedFileBase Ado_file { get; set; }

    }
}
