//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Available
    {
        public int Available_Id { get; set; }
        public string Item_Type { get; set; }
        public string Current_Location { get; set; }
        public string Collection { get; set; }
        public string Shelf_Number { get; set; }
        public string Status { get; set; }
        public int Barcode { get; set; }
        public int Item_fid { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
