//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrer
    {
        public int carrer_id { get; set; }
        public string carrer_name { get; set; }
        public string carrer_position { get; set; }
        public string carrer_qualification { get; set; }
        public string carrer_desc { get; set; }
    }
}
