//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Community
    {
        public int com_id { get; set; }
        public string com_name { get; set; }
        public string com_desc { get; set; }
        public string com_author { get; set; }
        public int com_price { get; set; }
    }
}
