//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Xml.Linq;

    public partial class Dbook
    {
        public int Ebooks_Id { get; set; }
        [Required(ErrorMessage = "Name Is Required")]
        [Display(Name = "Title")]
        public string Ebook_Name { get; set; }
        [Required(ErrorMessage = "Description Is Required")]
        [Display(Name = "Description")]
        public string Ebook_Decription { get; set; }
        [Required(ErrorMessage = "File Is Required")]
        [Display(Name = "Book Pdf")]
        public string Ebook_Pdf { get; set; }
       
        public HttpPostedFileBase Ebk_file { get; set; }
        [Required(ErrorMessage = "Author name Is Required")]
        [Display(Name = "Author")]

        public string Ebook_Author { get; set; }
    }
}
