//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbookTable
    {
        public int Ebook_ID { get; set; }
        public string Ebook_Name { get; set; }
        public string Ebook_Author { get; set; }
        public string Ebook_Desctiption { get; set; }
        public string Ebook_Subject { get; set; }
        public string Ebook_Publication { get; set; }
        public System.DateTime Ebook_year { get; set; }
        public string Ebook_Language { get; set; }
        public string Ebook_Pdf { get; set; }
        public string Ebook_Pages { get; set; }
    }
}
