//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int leave_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public System.DateTime date { get; set; }
        public string days { get; set; }
        public string reason { get; set; }
    }
}
