//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryDbEntities : DbContext
    {
        public LibraryDbEntities()
            : base("name=LibraryDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<carrer> carrers { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<Available> Availables { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<Community> Communities { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Videobook> Videobooks { get; set; }
        public virtual DbSet<AudioTable> AudioTables { get; set; }
    }
}
