//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Question
    {
        public int Q_id { get; set; }
        public string Subject { get; set; }
        public string Semester { get; set; }
        public string year { get; set; }
        public string Q_Pdf { get; set; }

        public HttpPostedFileBase Q_p { get; set; }
        public string Q_title { get; set; }
    }
}
