//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Req_ID { get; set; }
        public string Book_Name { get; set; }
        public string Book_Author { get; set; }
        public string Student_Name { get; set; }
        public string Student_Department { get; set; }
    }
}
