//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int Test_Id { get; set; }
        public string Test_Name { get; set; }
        public string Test_Batch { get; set; }
        public string Test_Description { get; set; }
        public string Test_Pic { get; set; }
    }
}
