//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Test
    {
        public int Test_id { get; set; }
        public string Test_Name { get; set; }
        public string Test_Dept { get; set; }
        public string Test_Review { get; set; }
        public string Test_Pic { get; set; }

        public HttpPostedFileBase T_pic { get; set; }

        //public HttpPostedFileBase T_pic { get; set; }


    }
}
