//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_Id { get; set; }
        public string User_Firstname { get; set; }
        public string User_Lastname { get; set; }
        public string User_Email { get; set; }
        public string User_Password { get; set; }
        public int User_Contact { get; set; }
        public string User_Department { get; set; }
    }
}
