//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Videobook
    {
        public int Video_ID { get; set; }
        public string Video_Name { get; set; }
        public string Video_File { get; set; }

        public HttpPostedFileBase Vdo_file { get; set; }

        //public HttpPostedFileBase Vdo_file { get; set; }
        public string Video_Description { get; set; }
        public string Video_Subject { get; set; }
    }
}
